name: mypy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy

    - name: Check for Python files and run mypy
      run: |
        if find . -name "*.py" | grep -q .; then
          echo "Python files found. Running mypy..."
          mypy .
        else
          echo "No Python files found. Skipping mypy."
        fi
